### ISSUE TITLE
Not using spaces between terms in defining a sort with multiple restrictions causes a syntax error

### ISSUE THREAD

**Issue by d4v3y5c0n3s** [githwxi/ATS-Postiats#270] opened 2021-11-11 02:12 UTC
_This does not compile:_
sortdef ImRpt = {ir:int | ir>=IMAGE_REPEAT_TILE && ir<=IMAGE_REPEAT_MIRROR}
_Error message:_
/home/tmj90/Goldelish-Engine/source/assets/image.sats: 726(line=24, offs=52) -- 729(line=24, offs=55): error(parsing): the keyword '}' is needed.
/home/tmj90/Goldelish-Engine/source/assets/image.sats: 691(line=24, offs=17) -- 692(line=24, offs=18): error(parsing): the syntactic entity [s0rtext] is needed.
/home/tmj90/Goldelish-Engine/source/assets/image.sats: 675(line=24, offs=1) -- 682(line=24, offs=8): error(parsing): the token is discarded.
exit(ATS): uncaught exception: _2tmp_2ATS_2dPostiats_2src_2pats_error_2esats__FatalErrorExn(1025)

_But this does:_
sortdef ImRpt = {ir:int | ir >= IMAGE_REPEAT_TILE && ir <= IMAGE_REPEAT_MIRROR}

(Note that "IMAGE_REPEAT_TILE" & "IMAGE_REPEAT_MIRROR" are macros defined to an integer value.)  Please let me know if you have any further questions.

**Comment by githwxi** [comment] 2021-11-11 12:34
The issue is due to 'ir<' being treated by the parser as the prefix of some template identifier; the parse expects to see a matching '>'. So a space between 'ir' and '<' is needed. BTW. this inconvenience has been fixed in ATS3.

**Comment by d4v3y5c0n3s** [comment] 2021-11-11 23:18
@githwxi Glad to hear this has been fixed in ATS3. 😄 Thanks!

**Closed** 2022-07-26 03:22 UTC
