### ISSUE TITLE
Code does not compile

### ISSUE THREAD

**Issue by antoyo** [githwxi/ATS-Postiats#174] opened 2017-08-07 20:05 UTC
Hi!
In the modularity chapter of the introduction, the following code does not compile:
```ats
implement swap_boxed{a,b} (xy) = (xy.1, xy.0)
```
And the same error happens for:
```ats
implement{a,b} swap_tmplt (xy) = (xy.1, xy.0)
```
And I'm not sure why because it is not in the source code.
Thanks to fix this issue.

**Comment by githwxi** [comment] 2017-08-07 21:24
Thanks for reporting it.

This seems to be ATS1 code.
If you write @(a, b) for (a, b) in the interface for swap_boxed, then the problem should go:

extern
fun
swap_boxed{a,b:type}(xy: @(a, b)): (b, a)

I will do a quick fix to remove this need and make it available in the next release.

**Comment by antoyo** [comment] 2017-08-11 19:32
I found another code that doesn't compile:
the [`rbtree_insert` function](https://github.com/ats-lang/ats-lang.github.io/blob/master/DOCUMENT/INT2PROGINATS/CODE/CHAP_DEPDTREF/rbtree.dats#L124).
There's a constraint that is not resolved.
Could you please fix it?

**Comment by githwxi** [comment] 2017-08-12 00:02
I just tried this example. It did typecheck and compile. What is the code you tried that did not typecheck?

**Comment by antoyo** [comment] 2017-08-12 03:50
The whole example also compiles from me, so it's probably again something that is missing from the tutorial.
No worries, I'll figure it out.

**Comment by githwxi** [comment] 2017-08-12 13:10
I found the typo:

[clr,v:int]

should be

[clr:int,v:int]

The problem is fixed now.

Thanks!

**Closed** 2017-10-03 19:45 UTC
